### ISSUE TITLE
[BUG]: setValue not working

### ISSUE THREAD

**Issue by maconic** [mpont91/vue3-vuetify-tests#1]
### Description of the bug

If you add a v-text-field like this in any component: 
        <v-text-field
            id="txtName"
            label="Name"
            required
        ></v-text-field>

Then try to set a value in a test like this:
        wrapper.find("#txtName").setValue("test")

You get a strange error

TypeError: el.animate is not a function
 ❯ __vite_ssr_import_9__.watch.flush node_modules/vuetify/lib/components/VField/VField.mjs:159:11

### Steps To Reproduce

Please see description. 

### Additional Information

Versions remained the same as in the repo.

**Comment by mpont91** [comment]
Hi @maconic, I tried to reproduce this bug, but in my case it still pass the tests. Can you look at this commit: https://github.com/mpont91/vue3-vuetify-tests/commit/99e84ade02b8af57ca63a5edc14e7f72b89632e3

**Comment by develmac** [comment]
Hi!

Sry got this myself running now!

Not sure what was wrong :( 

Cheers!
